Include All IfcBuildingElement Entities: true  # Set to true to include everything by default

# Common IfcBuildingElement subtypes
IfcBeam: true
IfcBearing: true
IfcBuildingElementProxy: true
IfcChimney: true
IfcColumn: true
IfcCovering: true
IfcCurtainWall: true
IfcDeepFoundatoin: true
IfcDoor: true
IfcFooting: true
IfcMember: true
IfcPlate: true
IfcPile: true
IfcRailing: true
IfcRamp: true
IfcRampFlight: true
IfcRoof: true
IfcShadingDevice: true
IfcSlab: true
IfcStair: true
IfcStairFlight: true
IfcWall: true
IfcWallStandardCase: true
IfcWindow: true


# IFC4 / IFC4.3 additional subtypes
IfcBridge: false
IfcBridgePart: false
IfcBearing: false
IfcCableCarrierSegment: false
IfcCableSegment: false
IfcDuctSegment: false
IfcDuctFitting: false
IfcPipeSegment: false
IfcPipeFitting: false
IfcDistributionChamberElement: false
IfcEnergyConversionDevice: false
IfcFlowFitting: false
IfcFlowSegment: false
IfcFlowTerminal: false
IfcFlowTreatmentDevice: false
IfcTank: false
IfcFurnishingElement: false
IfcTransportElement: false
IfcElementAssembly: false
IfcCivilElement: false
IfcMarineFacility: false
IfcBridgeStructure: false
IfcRail: false
IfcTrackElement: false
IfcSign: false
IfcSignal: false
IfcUtilityElement: false
